name: uros
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - cmake>=3.22
  - ninja
  - pkg-config
  - ccache
  - git
  - make
  - numpy
  - scipy
  - matplotlib
  - pyyaml
  - ipython

